CHARACTERS: {
    0: "N/A",
    1: "Riou",
    2: "Flik",
    3: "Viktor",
    4: "Viki",
    5: "Sheena",
    6: "Clive",
    7: "Hix",
    8: "Tengaar",
    9: "Futch",
    10: "Humphrey",
    11: "Georg",
    12: "Valeria",
    13: "Pesmerga",
    14: "Lorelai",
    15: "Shin",
    16: "Rikimaru",
    17: "Tomo",
    18: "Nanami",
    19: "Eilie",
    20: "Rina",
    21: "Bolgan",
    22: "Tuta",
    23: "Hanna",
    24: "Millie",
    25: "Karen",
    26: "Shiro",
    27: "Zamza",
    28: "Gengen",
    29: "Gabocha",
    30: "Kinnison",
    31: "Shilo",
    32: "Miklotov",
    33: "Camus",
    34: "Hauser",
    35: "Freed Y.",
    36: "Kahn",
    37: "Amada",
    38: "Tai Ho",
    39: "Anita",
    40: "Bob",
    41: "Meg",
    42: "Gadget",
    43: "Ayda",
    44: "Killey",
    45: "Sierra",
    46: "Oulan",
    47: "Genshu",
    48: "Mukumuku",
    49: "Abizboah",
    50: "Feather",
    51: "Badeaux",
    52: "Tsai",
    53: "Luc",
    54: "Chaco",
    55: "Nina",
    56: "Sid",
    57: "Yoshino",
    58: "Gijimu",
    59: "Koyu",
    60: "Lo Wen",
    61: "Mazus",
    62: "Sasuke",
    63: "Mondo",
    64: "Vincent",
    65: "Simone",
    66: "Hai Yo",
    67: "Stallion",
    68: "Wakaba",
    69: "Long Chan-Chan",
    70: "Gantetsu",
    71: "Hoi",
    72: "Siegfried",
    73: "Kasumi",
    74: "Rulodia",
    75: "Makumaku",
    76: "Mikumiku",
    77: "Mekumeku",
    78: "Mokumoku",
    79: "Chuchura",
    80: "Jowy",
    81: "Jowy 2",
    82: "McDohl",
    83: "Millie",
    84: "",
    85: "Apple",
    86: "Templeton",
    87: "Kiba",
    88: "Fitcher",
    89: "Shu",
    90: "Tetsu",
    91: "Leona",
    92: "Huan",
    93: "Jess",
    94: "Hilda",
    95: "Alex",
    96: "Emilia",
    97: "Tenkou",
    98: "Barbara",
    99: "Richmond",
    100: "Yam Koo",
    101: "Teresa",
    102: "Yuzu",
    103: "Taki",
    104: "Tony",
    105: "Adlai",
    106: "Gordon",
    107: "Hans",
    108: "Connell",
    109: "Lebrante",
    110: "Tessai",
    111: "Raura",
    112: "Annallee",
    113: "Pico",
    114: "Alberto",
    115: "Jude",
    116: "Jeane",
    117: "Ridley",
    118: "Klaus",
    119: "Maximillian",
    120: "Marlowe",
    121: "Gilbert",
    122: "Boris",
    123: "Pilika",
    124: "Pilika",
    125: "Gremio",
},
ITEMS: {
    0: "None",
    1: "Medicine",
    2: "Mega Medicine",
    3: "Antitoxin",
    4: "Throat Drops",
    5: "Needle",
    6: "Flaming Arrows",
    7: "Dancing Flames",
    8: "Fire Wall",
    9: "Kindness Drops",
    10: "Protect Mist",
    11: "Kindness Rain",
    12: "Wind of Sleep",
    13: "Healing Wind",
    14: "The Shredding",
    15: "Clay Guardian",
    16: "Revenge Earth",
    17: "Canopy Defense",
    18: "Angry Blow",
    19: "Thunder Runner",
    20: "Bolt of Wrath",
    21: "Stone of Power",
    22: "Stone of Magic",
    23: "Stone of Defense",
    24: "Stone of Magic-Defense",
    25: "Stone of Dexterity",
    26: "Stone of Speed",
    27: "Stone of Luck",
    28: "Dragon Censer",
    29: "Blinking Mirror",
    30: "Sacrifical Jizo",
    31: "Chick (Bath Set)",
    32: "Drinking Set",
    33: "Toy Boat",
    34: "Escape Talisma",
    35: "Suiko Marp",
    36: "Rag",
    37: "Oily Rag",
    38: "Rope",
    39: "Flint Stone",
    40: "Flint Stone",
    41: "Flour",
    42: "Wooden Amulet",
    43: "Healing Herb",
    44: "Reference Letter",
    45: "Highland Uniform",
    46: "Listening Hood?",
    47: "Iron Hammer",
    48: "Copper Hammer",
    49: "Silver Hammer",
    50: "Gold Hammer",
    51: "Round Plate",
    52: "Triangle Plate",
    53: "Square Plate",
    54: "Clay",
    55: "Listening Crystal",
    56: "Recipe #25",
    57: "Recipe #26",
    58: "Recipe #27",
    59: "Recipe #28",
    60: "Recipe #29",
    61: "Recipe #30",
    62: "Recipe #31",
    63: "Recipe #32",
    64: "Recipe #33",
    65: "Recipe #34",
    66: "Recipe #35",
    67: "Recipe #36",
    68: "Recipe #37",
    69: "Recipe #38",
    70: "Recipe #39",
    71: "Recipe #40",
    72: "Two Packages",
    73: "Leon's Letter",
    74: "Entry Permit",
    75: "Bath Set",
    76: "Sunglasses",
    77: "Dog Whistle",
    78: "Lubricating Oil",
    79: "Rose Bouquet",
    80: "Secret Writings",
    81: "Millet Dumplings",
    82: "Leisure Set",
    83: "Invincible Smile",
    84: "Sexy Wink",
    85: "Cup of the Oath"
},
FARMING: { //use_cnt 48
    0: "None",
    1: "Cabbage Seed",
    2: "Potato Seed",
    3: "Spinach Seed",
    4: "Tomato Seed",
    5: "Chick",
    6: "Piglet",
    7: "Lamb",
    8: "Calf",
},
TRADE: { //use_cnt 64
    0: "None",
    1: "Defective Urn",
    2: "Octopus Pot",
    3: "Flower Vase",
    4: "Wide Urn",
    5: "Blue Dragon Urn",
    6: "Celadon Urn",
    7: "Black Urn",
    8: "Fine China",
    9: "Persian Lamp",
    10: "Hex Doll",
    11: "Japanese Dish",
    12: "Chinese Dish",
    13: "Peeing Boy",
    14: "Bonsai Tree",
    15: "Knight Statue",
    16: "Goddess Statue",
    17: "Coral",
    18: "Graffiti",
    19: "Flower Painting",
    20: "Lover's Garden",
    21: "Landscape Scroll",
    22: "Beauties of Nature",
    23: "Sugar",
    24: "Salt",
    25: "Soy Sauce",
    26: "Mayonnaise",
    27: "Red Pepper",
    28: "Candle",
    29: "Fur",
    30: "Flute",
    31: "Wooden Amulet",
    32: "Native Costume",
    33: "Holly Berry",
    34: "Wine",
    35: "Deer Antler",
    36: "Book",
    37: "Musk",
    38: "Crystal Ball",
    39: "Pearl",
    40: "Ancient Text",
    41: "Gold Bar",
    42: "Karen Statue A",
    43: "Karen Statue B",
    44: "Karen Statue C",
    45: "Nanami's Vase",
    46: "Large Vase",
    47: "Genkaku's Vase",
},
BASE_ITEM: { //use_cnt 80
    0: "None",
    1: "Old book vol 1",
    2: "Old book vol 2",
    3: "Old book vol 3",
    4: "Old book vol 4",
    5: "Old book vol 5",
    6: "Old book vol 6",
    7: "Old book vol 7",
    8: "Old book vol 8",
    9: "Old book vol 9",
    10: "Old book vol 10",
    11: "Old book vol 11",
    12: "Old book vol 12",
    13: "Window Set 1",
    14: "Window Set 2",
    15: "Window Set 3",
    16: "Window Set 4",
    17: "Window Set 5",
    18: "Window Set 6",
    19: "Window Set 7",
    20: "Sound Set 1",
    21: "Sound Set 2",
    22: "Sound Set 3",
    23: "Sound Set 4",
    24: "Sound Set 5",
    25: "Sound Set 6",
    26: "Sound Set 7",
    27: "Dragon Plans 1",
    28: "Dragon Plans 2",
    29: "Dragon Plans 3",
    30: "Dragon Plans 4",
    31: "Unicorn Plans 1",
    32: "Unicorn Plans 2",
    33: "Unicorn Plans 3",
    34: "Unicorn Plans 4",
    35: "Rabbit Plans 1",
    36: "Rabbit Plans 2",
    37: "Rabbit Plans 3",
    38: "Rabbit Plans 4",
    39: "Turtle Plans 1",
    40: "Turtle Plans 2",
    41: "Turtle Plans 3",
    42: "Turtle Plans 4",
    43: "Recipe#1",
    44: "Recipe#2",
    45: "Recipe#3",
    46: "Recipe#4",
    47: "Recipe#5",
    48: "Recipe#6",
    49: "Recipe#7",
    50: "Recipe#8",
    51: "Recipe#9",
    52: "Recipe#10",
    53: "Recipe#11",
    54: "Recipe#12",
    55: "Recipe#13",
    56: "Recipe#14",
    57: "Recipe#15",
    58: "Recipe#16",
    59: "Recipe#17",
    60: "Recipe#18",
    61: "Recipe#19",
    62: "Recipe#20",
    63: "Recipe#21",
    64: "Recipe#22",
    65: "Recipe#23",
    66: "Recipe#24"
},
FOOD: { // use_cnt >= 99
    0: "None",
    1: "Tamago-Yaki",
    2: "Sweet Omelet",
    3: "Adult Fried Egg",
    4: "Fried Egg",
    5: "Egg Mayo Roll",
    6: "Eggsplosive",
    7: "Tomato Soup",
    8: "Tomato Juice",
    9: "Raw Tomato",
    10: "Tomato Miso Soup",
    11: "Tomato Salad",
    12: "Red Hot Tomatoes",
    13: "Ohitashi",
    14: "Spinach Cake",
    15: "Spinach Juice",
    16: "Spinach Saute",
    17: "Spinach Salad",
    18: "Spicy Stir Fry",
    19: "Salad",
    20: "Sweet Salad",
    21: "Pickled Cabbage",
    22: "Island Salad",
    23: "Green Salad",
    24: "Veggie Stir Fry",
    25: "Gyoza",
    26: "Fruit Gyoza",
    27: "Steamed Gyoza",
    28: "Fried Gyoza",
    29: "Deep-Fried Gyoza",
    30: "Szechuan Gyoza",
    31: "Chowder",
    32: "Potato Pudding",
    33: "Vichyssoise",
    34: "Dark Chowder",
    35: "Egg Soup",
    36: "Gumbo",
    37: "BBQ Meat Bun",
    38: "Sweet Bean Bun",
    39: "Ginger Beef Bun",
    40: "Ma Bo Bun",
    41: "Pirate's Bun",
    42: "Pizza Bun",
    43: "Buttered Clams",
    44: "Clam Pudding",
    45: "Grilled Scallops",
    46: "Steamed Abalone",
    47: "Clam Mayonnaise",
    48: "Mai Mai??",
    49: "Fish Fry",
    50: "Fish Donuts",
    51: "Deep-Fried Fish",
    52: "Tatsuta Age",
    53: "French Fries",
    54: "Fried Tacos",
    55: "Ice Cream",
    56: "Pudding",
    57: "Nanami Ice",
    58: "Soy Ice",
    59: "Fried Ice Cream",
    60: "Red Pepper Ice",
    61: "Quiche",
    62: "Pineapple Rice",
    63: "Egg Porridge",
    64: "Baked Mochi",
    65: "Cream Quiche",
    66: "Lasagna",
    67: "Sandwich",
    68: "French Toast",
    69: "Steak Sandwich",
    70: "Teriyaki Sandwich",
    71: "Veggie Sandwich",
    72: "Spicy Sandwich",
    73: "Meat Pie",
    74: "Cream Pie",
    75: "Meringue Pie",
    76: "Kobold Pie",
    77: "Mayonnaise Pie",
    78: "Chili Pie",
    79: "Simmered Fish",
    80: "Simmered Carp",
    81: "Tai-Chili Style",
    82: "Sole",
    83: "Fish with Sauce",
    84: "Blackened Sole",
    85: "Fried Fish Balls",
    86: "Sweet&Sour Fish",
    87: "Crab Cakes",
    88: "Meatballs",
    89: "Greasy Fish",
    90: "Fiery Fish Balls",
    91: "Sunomono",
    92: "Sour Shrimp",
    93: "Nonpei Sunomono",
    94: "Gourmet Sunomono",
    95: "Weird Sunomono",
    96: "Cajun Shrimp",
    97: "Cake",
    98: "Short Cake",
    99: "Nanami Cake",
    100: "Black Cake",
    101: "Cheesecake",
    102: "Fire Cake",
    103: "Croquettes",
    104: "Sweet Croquettes",
    105: "Eilie Croquettes",
    106: "Black Croquettes",
    107: "Cream Croquettes",
    108: "Hot Croquettes",
    109: "Pasta",
    110: "Kiddie Pasta",
    111: "Pasta Parmesan",
    112: "Downtown Pasta",
    113: "Pasta Salad",
    114: "Chili Pasta",
    115: "Tempura",
    116: "Snack Tempura",
    117: "Real Tempura",
    118: "Tempura-Don",
    119: "Amazing Tempura",
    120: "Spicy Tempura",
    121: "Grilled Fish",
    122: "Broiled Eel",
    123: "Salted Fish",
    124: "Dried Fish",
    125: "Salmon Meunire",
    126: "Grilled Red Fish",
    127: "Gratin",
    128: "Apple Gratin",
    129: "Salty Gratin",
    130: "Crispy Gratin",
    131: "Creamy Gratin",
    132: "Chili Gratin",
    133: "Rice Omelet",
    134: "Kid\'s Lunch",
    135: "Salty Omelet",
    136: "Soy Rice Omelet",
    137: "Mayo Rice Omelet",
    138: "Red Pepper Rice",
    139: "Fried Rice",
    140: "Shrimp Pilaf",
    141: "Salty Fried Rice",
    142: "Gunpowder Rice",
    143: "Heavy Pilaf",
    144: "Spicy Pilaf",
    145: "Pizza",
    146: "Pancakes",
    147: "Anchovy Pizza",
    148: "Senbei",
    149: "Okonomiyaki",
    150: "Spicy Pizza",
    151: "Teriyaki",
    152: "Sweet Teriyaki",
    153: "Hot Spareribs",
    154: "Mild Teriyaki",
    155: "Teri-Cream",
    156: "BBQ-Bomb",
    157: "Tonkatsu",
    158: "Meat and Potato",
    159: "Ginger Pork",
    160: "Soy Cutlet",
    161: "Cream Cutlets",
    162: "Spicy Cutlets",
    163: "Curry Rice",
    164: "Kiddie Curry",
    165: "Salty Curry",
    166: "Japanese Curry",
    167: "Creamy Curry",
    168: "Red Curry",
    169: "Grilled Beef",
    170: "Sukiyaki",
    171: "Grilled Tongue",
    172: "Beef Rice Bowl",
    173: "Meat Salad",
    174: "Chige Nabe",
    175: "Ramen",
    176: "Chinese Noodles",
    177: "Salty Ramen",
    178: "Soy Sauce Ramen",
    179: "Gourmet Ramen",
    180: "Red Hot Ramen",
    181: "Hamburger",
    182: "Sugar-Cured Meat",
    183: "Kobold Burger",
    184: "Japan Burger",
    185: "Tinto Burger",
    186: "Surprise Burger",
    187: "Obento",
    188: "Ladie\'s Lunch",
    189: "Rising Sun Bento",
    190: "Sashimi Bento",
    191: "Diet Lunch",
    192: "Shrimp Lunch",
    193: "Sushi",
    194: "Chirashi-Zashi",
    195: "Salty Rice Ball",
    196: "Fancy Rice Ball",
    197: "French Roll",
    198: "Tekka-don",
    199: "Japanese Stew",
    200: "Sweet Tofu",
    201: "Bouillabaise",
    202: "Shabu Shabu",
    203: "Dark Stew",
    204: "Spicy Stew",
    205: "Full Course",
    206: "Elf Course",
    207: "Kobold Course",
    208: "Rokkaku Course",
    209: "Matilda Course",
    210: "Tinto Specialty",
    211: "Genghis Khan",
    212: "Fa Chu Chin",
    213: "Coopa",
    214: "Genghis Stew",
    215: "Cream Stew",
    216: "Tom Yum Stew",
    217: "Steak",
    218: "Sweet Steak",
    219: "Beefsteak",
    220: "Japanese Steak",
    221: "Piccata",
    222: "Pepper Steak",
    223: "Sashimi Combo",
    224: "Queen of the Sea",
    225: "Sea Treasure",
    226: "Ship Combo",
    227: "Salad Combo",
    228: "Spicy Sashimi",
    229: "Special Stew",
    230: "Sweet Syrup",
    231: "Adult Stew",
    232: "Clear or Cream Soup",
    233: "Mellow Stew",
    234: "Spicy Stew",
    235: "Kaiseki Dinner",
    236: "Candy House",
    237: "Salt House",
    238: "Complete Kaiseki",
    239: "Special Salad",
    240: "Flaming Sea Special",
},
HELMET: {
    0: "None",
    1: "Bandana",
    2: "Leather Hat",
    3: "Wind Feather Ornament",
    4: "Pointed Hat",
    5: "Circlet",
    6: "Half Helmet",
    7: "Headgear",
    8: "Silver Hat",
    9: "Full Helmet",
    10: "Wind Hat",
    11: "Flame Helmet",
    12: "Horned Helmet",
    85: "Mole Helmet",
},
ARMOR: {
    0: "None",
    13: "Robe",
    14: "Tunic",
    15: "Fur Coat",
    16: "Chest Plate",
    17: "Guard Robe",
    18: "Martial Arts Robe",
    19: "Leather Armor",
    20: "Chain Mail",
    21: "Ninja Garb",
    22: "Half Plate",
    23: "Magic Robe",
    24: "Thunder God's Garb",
    25: "Scale Mail",
    26: "Dragon Armor",
    27: "Master's Robe",
    28: "Full Plate",
    29: "Taikyoku Tunic",
    30: "Master's Garb",
    31: "Fog Robe",
    32: "Earth Armor",
    33: "Dream Robe",
    34: "Silver Dragon Armor",
    35: "Knight Armor",
    36: "Blood Armor",
    37: "Windspun Armor",
    86: "Mole Suit",
},
SHIELD: {
    0: "None",
    38: "Wooden Shield",
    39: "Iron Shield",
    40: "Kite Shield",
    41: "Main-Gauche",
    42: "Silver Shield",
    43: "Chaos Shield",
    44: "Earth Shield",
    87: "Mole Shield",
},
OTHER_EQUIP: {
    0: "None",
    45: "Wooden Shoes",
    46: "Boots",
    47: "Toe Shoes",
    48: "Winged Boots",
    49: "Iron Boots",
    50: "Gloves",
    51: "Gauntlet",
    52: "Silverlet",
    53: "Power Gloves",
    54: "Goldlet",
    55: "Cape",
    56: "Leather Cape",
    57: "Fur Cape",
    58: "Cape of Darkness",
    59: "Crimson Cape",
    60: "Collar",
    61: "Heavy Collar",
    62: "Silver Collar",
    63: "Gold Collar",
    64: "Wing Ornament",
    65: "Greaves",
    66: "Shoulder Pads",
    67: "Cheeks Guards",
    68: "Belt of Strength",
    69: "Fire Emblem",
    70: "Gold Emblem",
    71: "Blue Ribbon",
    72: "Star Earrings",
    73: "Sun Badge",
    74: "Fish Badge",
    75: "Rose Brooch",
    76: "Water Amulet",
    77: "Thunder Amulet",
    78: "Wind Amulet",
    79: "Guard Ring",
    80: "Magic Ring",
    81: "Speed Ring",
    82: "Power Ring",
    83: "Skill Ring",
    84: "Lucky Ring",
},
RUNES: {
    0: "None",
    1: "Fire Orb",
    2: "Rage Orb",
    3: "Water Orb",
    4: "Flowing Orb",
    5: "Wind Orb", //correct
    6: "Cyclone Orb",
    7: "Earth Orb",
    8: "Mother Earth Orb",
    9: "Lightning Orb",
    10: "Thunder Orb",
    11: "Soul Eater",
    12: "Resurrection Orb",
    13: "Bright Shield Orb", //correct
    14: "Black Sword Orb", //correct
    15: "Blinking Orb",
    16: "Darkness Orb",
    17: "Blue Gate Orb", //correct
    18: "White Saint Orb",
    19: "Titan Orb",
    20: "Viper Orb",
    21: "Great Hawk Orb", //correct
    22: "Lion Orb",
    23: "Kite Orb",
    24: "Unicorn Orb",
    25: "Gozu Orb",
    26: "Pixie Orb",
    27: "Banshee Orb",
    28: "Sylph Orb",
    29: "Chimera Orb",
    30: "Nymph Orb",
    31: "Dryad Orb",
    // jump
    39: "Gadget Orb",
    40: "Shrike Orb",
    41: "Falcon Orb", //should be 41
    42: "Mayfly Orb",
    43: "Swallow Orb",
    44: "Fire Breath Orb",
    45: "Groundhog Orb",
    46: "Fire Dragon Orb",
    47: "Shining Wind Orb",
    48: "Blue Drop Orb",
    49: "White Tiger Orb",
    50: "Howling Orb",
    51: "Spider Slay Orb",
    52: "Angry Dragon Orb", //should be 52
    53: "Twin Ring Orb",
    54: "Rabid Fang Orb",
    //jump
    62: "Fortune Orb",
    63: "Prosperity Orb",
    64: "Champion's Orb",
    65: "Double-Jab Orb",
    66: "Killer Orb",
    67: "Counter Orb",
    68: "Spark Orb",
    69: "Gale Orb",
    70: "Sunbeam Orb",
    71: "Phero Orb",
    72: "Knight Orb",
    73: "Wall Orb",
    74: "Haziness Orb",
    75: "Drain Orb",
    76: "Barrier Orb",
    77: "Balance Orb",
    78: "Fire Sealing Orb",
    79: "Skunk Orb",
    80: "Firefly Orb",
    81: "Medicine Orb", //this should be 81
    82: "Double-Edged Orb",
    83: "Wizard Orb", //this should be 83
    84: "Warrior Orb",
    85: "Waking Orb",
    86: "Alertness Orb",
    87: "Fury Orb", //this should be 87
    88: "Violence Orb",
    89: "Godspeed Orb", //this should be 89
    // jump
    92: "Fire Lizard Orb",
    93: "Magic Drain Orb",
    94: "Hunter Orb",
    95: "Technique Orb",
    96: "Silence Orb",
    97: "Poison Orb", //should be 97
    98: "Knockdown Orb",
    99: "Sleep Orb",
    100: "Friendship Orb",
    101: "Solitude Orb",
    102: "Kindness Orb", //should be 102
    103: "Exertion Orb",
},